/*

 SRC/ROAD3DANIM.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 749

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Road3DAnimBank 0

/* Super Gameboy palette 0 */
#define Road3DAnimSGBPal0c0 6076
#define Road3DAnimSGBPal0c1 8935
#define Road3DAnimSGBPal0c2 6596
#define Road3DAnimSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Road3DAnimSGBPal1c0 6076
#define Road3DAnimSGBPal1c1 8935
#define Road3DAnimSGBPal1c2 6596
#define Road3DAnimSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Road3DAnimSGBPal2c0 6076
#define Road3DAnimSGBPal2c1 8935
#define Road3DAnimSGBPal2c2 6596
#define Road3DAnimSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Road3DAnimSGBPal3c0 6076
#define Road3DAnimSGBPal3c1 8935
#define Road3DAnimSGBPal3c2 6596
#define Road3DAnimSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Road3DAnimCGBPal0c0 31536
#define Road3DAnimCGBPal0c1 30240
#define Road3DAnimCGBPal0c2 32767
#define Road3DAnimCGBPal0c3 801

/* Gameboy Color palette 1 */
#define Road3DAnimCGBPal1c0 21461
#define Road3DAnimCGBPal1c1 896
#define Road3DAnimCGBPal1c2 1632
#define Road3DAnimCGBPal1c3 16912

/* Gameboy Color palette 2 */
#define Road3DAnimCGBPal2c0 32767
#define Road3DAnimCGBPal2c1 896
#define Road3DAnimCGBPal2c2 1632
#define Road3DAnimCGBPal2c3 16912

/* Gameboy Color palette 3 */
#define Road3DAnimCGBPal3c0 31536
#define Road3DAnimCGBPal3c1 30240
#define Road3DAnimCGBPal3c2 32767
#define Road3DAnimCGBPal3c3 801

/* Gameboy Color palette 4 */
#define Road3DAnimCGBPal4c0 31536
#define Road3DAnimCGBPal4c1 30240
#define Road3DAnimCGBPal4c2 32767
#define Road3DAnimCGBPal4c3 801

/* Gameboy Color palette 5 */
#define Road3DAnimCGBPal5c0 31536
#define Road3DAnimCGBPal5c1 30240
#define Road3DAnimCGBPal5c2 32767
#define Road3DAnimCGBPal5c3 801

/* Gameboy Color palette 6 */
#define Road3DAnimCGBPal6c0 31536
#define Road3DAnimCGBPal6c1 30240
#define Road3DAnimCGBPal6c2 32767
#define Road3DAnimCGBPal6c3 801

/* Gameboy Color palette 7 */
#define Road3DAnimCGBPal7c0 0
#define Road3DAnimCGBPal7c1 0
#define Road3DAnimCGBPal7c2 32767
#define Road3DAnimCGBPal7c3 16912
/* CGBpalette entries. */
extern unsigned char Road3DAnimCGB[];
/* Start of tile array. */
extern unsigned char Road3DAnim[];

/* End of SRC/ROAD3DANIM.H */
