/*

 COG3D_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 12

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Cog3D_TilesBank 0

/* Super Gameboy palette 0 */
#define Cog3D_TilesSGBPal0c0 6076
#define Cog3D_TilesSGBPal0c1 8935
#define Cog3D_TilesSGBPal0c2 6596
#define Cog3D_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Cog3D_TilesSGBPal1c0 6076
#define Cog3D_TilesSGBPal1c1 8935
#define Cog3D_TilesSGBPal1c2 6596
#define Cog3D_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Cog3D_TilesSGBPal2c0 6076
#define Cog3D_TilesSGBPal2c1 8935
#define Cog3D_TilesSGBPal2c2 6596
#define Cog3D_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Cog3D_TilesSGBPal3c0 6076
#define Cog3D_TilesSGBPal3c1 8935
#define Cog3D_TilesSGBPal3c2 6596
#define Cog3D_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Cog3D_TilesCGBPal0c0 10753
#define Cog3D_TilesCGBPal0c1 24311
#define Cog3D_TilesCGBPal0c2 14798
#define Cog3D_TilesCGBPal0c3 6342

/* Gameboy Color palette 1 */
#define Cog3D_TilesCGBPal1c0 6342
#define Cog3D_TilesCGBPal1c1 1162
#define Cog3D_TilesCGBPal1c2 1125
#define Cog3D_TilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Cog3D_TilesCGBPal2c0 14798
#define Cog3D_TilesCGBPal2c1 308
#define Cog3D_TilesCGBPal2c2 207
#define Cog3D_TilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Cog3D_TilesCGBPal3c0 14798
#define Cog3D_TilesCGBPal3c1 9887
#define Cog3D_TilesCGBPal3c2 410
#define Cog3D_TilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Cog3D_TilesCGBPal4c0 24311
#define Cog3D_TilesCGBPal4c1 6975
#define Cog3D_TilesCGBPal4c2 729
#define Cog3D_TilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Cog3D_TilesCGBPal5c0 24311
#define Cog3D_TilesCGBPal5c1 32767
#define Cog3D_TilesCGBPal5c2 18366
#define Cog3D_TilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Cog3D_TilesCGBPal6c0 23575
#define Cog3D_TilesCGBPal6c1 29722
#define Cog3D_TilesCGBPal6c2 29719
#define Cog3D_TilesCGBPal6c3 26650

/* Gameboy Color palette 7 */
#define Cog3D_TilesCGBPal7c0 23648
#define Cog3D_TilesCGBPal7c1 23648
#define Cog3D_TilesCGBPal7c2 32767
#define Cog3D_TilesCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char Cog3D_TilesCGB[];
/* Start of tile array. */
extern const unsigned char Cog3D_Tiles[];

/* End of COG3D_TILES.H */
