/*

 COG3D_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 25
   Tile set      : 6_Cog3D_Tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Cog3D_MapWidth 20
#define Cog3D_MapHeight 25
#define Cog3D_MapBank 0

#define Cog3D_Map Cog3D_MapPLN0
extern const unsigned char Cog3D_MapPLN0[];
extern const unsigned char Cog3D_MapPLN1[];

/* End of COG3D_MAP.H */
