/*

 SRC/COG3D_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Cog3D_TilesBank 0

/* Super Gameboy palette 0 */
#define Cog3D_TilesSGBPal0c0 6076
#define Cog3D_TilesSGBPal0c1 8935
#define Cog3D_TilesSGBPal0c2 6596
#define Cog3D_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Cog3D_TilesSGBPal1c0 6076
#define Cog3D_TilesSGBPal1c1 8935
#define Cog3D_TilesSGBPal1c2 6596
#define Cog3D_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Cog3D_TilesSGBPal2c0 6076
#define Cog3D_TilesSGBPal2c1 8935
#define Cog3D_TilesSGBPal2c2 6596
#define Cog3D_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Cog3D_TilesSGBPal3c0 6076
#define Cog3D_TilesSGBPal3c1 8935
#define Cog3D_TilesSGBPal3c2 6596
#define Cog3D_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Cog3D_TilesCGBPal0c0 12684
#define Cog3D_TilesCGBPal0c1 5285
#define Cog3D_TilesCGBPal0c2 636
#define Cog3D_TilesCGBPal0c3 17214

/* Gameboy Color palette 1 */
#define Cog3D_TilesCGBPal1c0 27482
#define Cog3D_TilesCGBPal1c1 12684
#define Cog3D_TilesCGBPal1c2 20318
#define Cog3D_TilesCGBPal1c3 30718

/* Gameboy Color palette 2 */
#define Cog3D_TilesCGBPal2c0 21140
#define Cog3D_TilesCGBPal2c1 0
#define Cog3D_TilesCGBPal2c2 337
#define Cog3D_TilesCGBPal2c3 671

/* Gameboy Color palette 3 */
#define Cog3D_TilesCGBPal3c0 12684
#define Cog3D_TilesCGBPal3c1 705
#define Cog3D_TilesCGBPal3c2 1377
#define Cog3D_TilesCGBPal3c3 6336

/* Gameboy Color palette 4 */
#define Cog3D_TilesCGBPal4c0 27482
#define Cog3D_TilesCGBPal4c1 705
#define Cog3D_TilesCGBPal4c2 1377
#define Cog3D_TilesCGBPal4c3 6336

/* Gameboy Color palette 5 */
#define Cog3D_TilesCGBPal5c0 21140
#define Cog3D_TilesCGBPal5c1 705
#define Cog3D_TilesCGBPal5c2 1377
#define Cog3D_TilesCGBPal5c3 6336

/* Gameboy Color palette 6 */
#define Cog3D_TilesCGBPal6c0 125
#define Cog3D_TilesCGBPal6c1 23575
#define Cog3D_TilesCGBPal6c2 14384
#define Cog3D_TilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Cog3D_TilesCGBPal7c0 6016
#define Cog3D_TilesCGBPal7c1 23575
#define Cog3D_TilesCGBPal7c2 14384
#define Cog3D_TilesCGBPal7c3 0
/* CGBpalette entries. */
//extern unsigned char Cog3D_TilesCGB[];
/* Start of tile array. */
extern unsigned char Cog3D_Tiles[];

/* End of SRC/COG3D_TILES.H */
