/*

 SRC/COG_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 63

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Cog_TilesBank 0

/* Super Gameboy palette 0 */
#define Cog_TilesSGBPal0c0 6076
#define Cog_TilesSGBPal0c1 8935
#define Cog_TilesSGBPal0c2 6596
#define Cog_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Cog_TilesSGBPal1c0 6076
#define Cog_TilesSGBPal1c1 8935
#define Cog_TilesSGBPal1c2 6596
#define Cog_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Cog_TilesSGBPal2c0 6076
#define Cog_TilesSGBPal2c1 8935
#define Cog_TilesSGBPal2c2 6596
#define Cog_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Cog_TilesSGBPal3c0 6076
#define Cog_TilesSGBPal3c1 8935
#define Cog_TilesSGBPal3c2 6596
#define Cog_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Cog_TilesCGBPal0c0 18112
#define Cog_TilesCGBPal0c1 31572
#define Cog_TilesCGBPal0c2 29984
#define Cog_TilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Cog_TilesCGBPal1c0 18112
#define Cog_TilesCGBPal1c1 27358
#define Cog_TilesCGBPal1c2 17433
#define Cog_TilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Cog_TilesCGBPal2c0 18112
#define Cog_TilesCGBPal2c1 23486
#define Cog_TilesCGBPal2c2 636
#define Cog_TilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Cog_TilesCGBPal3c0 18112
#define Cog_TilesCGBPal3c1 24535
#define Cog_TilesCGBPal3c2 4640
#define Cog_TilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Cog_TilesCGBPal4c0 18112
#define Cog_TilesCGBPal4c1 25368
#define Cog_TilesCGBPal4c2 14798
#define Cog_TilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Cog_TilesCGBPal5c0 18112
#define Cog_TilesCGBPal5c1 25368
#define Cog_TilesCGBPal5c2 14798
#define Cog_TilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Cog_TilesCGBPal6c0 18112
#define Cog_TilesCGBPal6c1 25368
#define Cog_TilesCGBPal6c2 14798
#define Cog_TilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Cog_TilesCGBPal7c0 18112
#define Cog_TilesCGBPal7c1 25368
#define Cog_TilesCGBPal7c2 14798
#define Cog_TilesCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char Cog_TilesCGB[];
/* Start of tile array. */
extern const unsigned char Cog_Tiles[];

/* End of SRC/COG_TILES.H */
