/*

 SRC/COG_MAP.H

 Map Include File.

 Info:
   Section       : Map
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : 5_Cog_Tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Cog_MapWidth 20
#define Cog_MapHeight 18
#define Cog_MapBank 0

#define Cog_Map Cog_MapPLN0
extern const unsigned char Cog_MapPLN0[];
extern const unsigned char Cog_MapPLN1[];

/* End of SRC/COG_MAP.H */
