/*

 SRC/COG_TILES_ANIM.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 607

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Cog_Tiles_AnimBank 0

/* Super Gameboy palette 0 */
#define Cog_Tiles_AnimSGBPal0c0 6076
#define Cog_Tiles_AnimSGBPal0c1 8935
#define Cog_Tiles_AnimSGBPal0c2 6596
#define Cog_Tiles_AnimSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Cog_Tiles_AnimSGBPal1c0 6076
#define Cog_Tiles_AnimSGBPal1c1 8935
#define Cog_Tiles_AnimSGBPal1c2 6596
#define Cog_Tiles_AnimSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Cog_Tiles_AnimSGBPal2c0 6076
#define Cog_Tiles_AnimSGBPal2c1 8935
#define Cog_Tiles_AnimSGBPal2c2 6596
#define Cog_Tiles_AnimSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Cog_Tiles_AnimSGBPal3c0 6076
#define Cog_Tiles_AnimSGBPal3c1 8935
#define Cog_Tiles_AnimSGBPal3c2 6596
#define Cog_Tiles_AnimSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Cog_Tiles_AnimCGBPal0c0 18112
#define Cog_Tiles_AnimCGBPal0c1 25368
#define Cog_Tiles_AnimCGBPal0c2 14798
#define Cog_Tiles_AnimCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Cog_Tiles_AnimCGBPal1c0 18112
#define Cog_Tiles_AnimCGBPal1c1 25368
#define Cog_Tiles_AnimCGBPal1c2 14798
#define Cog_Tiles_AnimCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Cog_Tiles_AnimCGBPal2c0 18112
#define Cog_Tiles_AnimCGBPal2c1 25368
#define Cog_Tiles_AnimCGBPal2c2 14798
#define Cog_Tiles_AnimCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Cog_Tiles_AnimCGBPal3c0 18112
#define Cog_Tiles_AnimCGBPal3c1 25368
#define Cog_Tiles_AnimCGBPal3c2 14798
#define Cog_Tiles_AnimCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Cog_Tiles_AnimCGBPal4c0 18112
#define Cog_Tiles_AnimCGBPal4c1 25368
#define Cog_Tiles_AnimCGBPal4c2 14798
#define Cog_Tiles_AnimCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Cog_Tiles_AnimCGBPal5c0 18112
#define Cog_Tiles_AnimCGBPal5c1 25368
#define Cog_Tiles_AnimCGBPal5c2 14798
#define Cog_Tiles_AnimCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Cog_Tiles_AnimCGBPal6c0 18112
#define Cog_Tiles_AnimCGBPal6c1 25368
#define Cog_Tiles_AnimCGBPal6c2 14798
#define Cog_Tiles_AnimCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Cog_Tiles_AnimCGBPal7c0 18112
#define Cog_Tiles_AnimCGBPal7c1 25368
#define Cog_Tiles_AnimCGBPal7c2 14798
#define Cog_Tiles_AnimCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char Cog_Tiles_AnimCGB[];
/* Start of tile array. */
extern const unsigned char Cog_Tiles_Anim[];

/* End of SRC/COG_TILES_ANIM.H */
