/*

 SRC/CREDITS_SPRITES_ANIM.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 63

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Credits_Sprites_AnimBank 0

/* Super Gameboy palette 0 */
#define Credits_Sprites_AnimSGBPal0c0 6076
#define Credits_Sprites_AnimSGBPal0c1 8935
#define Credits_Sprites_AnimSGBPal0c2 6596
#define Credits_Sprites_AnimSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Credits_Sprites_AnimSGBPal1c0 6076
#define Credits_Sprites_AnimSGBPal1c1 8935
#define Credits_Sprites_AnimSGBPal1c2 6596
#define Credits_Sprites_AnimSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Credits_Sprites_AnimSGBPal2c0 6076
#define Credits_Sprites_AnimSGBPal2c1 8935
#define Credits_Sprites_AnimSGBPal2c2 6596
#define Credits_Sprites_AnimSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Credits_Sprites_AnimSGBPal3c0 6076
#define Credits_Sprites_AnimSGBPal3c1 8935
#define Credits_Sprites_AnimSGBPal3c2 6596
#define Credits_Sprites_AnimSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Credits_Sprites_AnimCGBPal0c0 32767
#define Credits_Sprites_AnimCGBPal0c1 2911
#define Credits_Sprites_AnimCGBPal0c2 1224
#define Credits_Sprites_AnimCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Credits_Sprites_AnimCGBPal1c0 32767
#define Credits_Sprites_AnimCGBPal1c1 27520
#define Credits_Sprites_AnimCGBPal1c2 10282
#define Credits_Sprites_AnimCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Credits_Sprites_AnimCGBPal2c0 0
#define Credits_Sprites_AnimCGBPal2c1 28606
#define Credits_Sprites_AnimCGBPal2c2 32117
#define Credits_Sprites_AnimCGBPal2c3 16426

/* Gameboy Color palette 3 */
#define Credits_Sprites_AnimCGBPal3c0 0
#define Credits_Sprites_AnimCGBPal3c1 12684
#define Credits_Sprites_AnimCGBPal3c2 21140
#define Credits_Sprites_AnimCGBPal3c3 32767

/* Gameboy Color palette 4 */
#define Credits_Sprites_AnimCGBPal4c0 0
#define Credits_Sprites_AnimCGBPal4c1 12684
#define Credits_Sprites_AnimCGBPal4c2 21140
#define Credits_Sprites_AnimCGBPal4c3 32767

/* Gameboy Color palette 5 */
#define Credits_Sprites_AnimCGBPal5c0 0
#define Credits_Sprites_AnimCGBPal5c1 12684
#define Credits_Sprites_AnimCGBPal5c2 21140
#define Credits_Sprites_AnimCGBPal5c3 32767

/* Gameboy Color palette 6 */
#define Credits_Sprites_AnimCGBPal6c0 0
#define Credits_Sprites_AnimCGBPal6c1 12684
#define Credits_Sprites_AnimCGBPal6c2 21140
#define Credits_Sprites_AnimCGBPal6c3 32767

/* Gameboy Color palette 7 */
#define Credits_Sprites_AnimCGBPal7c0 0
#define Credits_Sprites_AnimCGBPal7c1 12684
#define Credits_Sprites_AnimCGBPal7c2 21140
#define Credits_Sprites_AnimCGBPal7c3 32767
/* CGBpalette entries. */
extern unsigned char Credits_Sprites_AnimCGB[];
/* Start of tile array. */
extern unsigned char Credits_Sprites_Anim[];

/* End of SRC/CREDITS_SPRITES_ANIM.H */
