/*

 SRC/CREDITS_MAP.H

 Map Include File.

 Info:
   Section       : Map
   Bank          : 0
   Map size      : 20 x 308
   Tile set      : 15_Credits_Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Credits_MapWidth 20
#define Credits_MapHeight 308
#define Credits_MapBank 0

extern unsigned char Credits_Map[];

/* End of SRC/CREDITS_MAP.H */
