/*

 SRC/CREDITS_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 232

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Credits_TilesBank 0

/* Super Gameboy palette 0 */
#define Credits_TilesSGBPal0c0 6076
#define Credits_TilesSGBPal0c1 8935
#define Credits_TilesSGBPal0c2 6596
#define Credits_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Credits_TilesSGBPal1c0 6076
#define Credits_TilesSGBPal1c1 8935
#define Credits_TilesSGBPal1c2 6596
#define Credits_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Credits_TilesSGBPal2c0 6076
#define Credits_TilesSGBPal2c1 8935
#define Credits_TilesSGBPal2c2 6596
#define Credits_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Credits_TilesSGBPal3c0 6076
#define Credits_TilesSGBPal3c1 8935
#define Credits_TilesSGBPal3c2 6596
#define Credits_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Credits_TilesCGBPal0c0 32767
#define Credits_TilesCGBPal0c1 24286
#define Credits_TilesCGBPal0c2 12575
#define Credits_TilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Credits_TilesCGBPal1c0 32767
#define Credits_TilesCGBPal1c1 24286
#define Credits_TilesCGBPal1c2 12575
#define Credits_TilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Credits_TilesCGBPal2c0 32767
#define Credits_TilesCGBPal2c1 24286
#define Credits_TilesCGBPal2c2 12575
#define Credits_TilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Credits_TilesCGBPal3c0 32767
#define Credits_TilesCGBPal3c1 24286
#define Credits_TilesCGBPal3c2 12575
#define Credits_TilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Credits_TilesCGBPal4c0 32767
#define Credits_TilesCGBPal4c1 24286
#define Credits_TilesCGBPal4c2 12575
#define Credits_TilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Credits_TilesCGBPal5c0 32767
#define Credits_TilesCGBPal5c1 24286
#define Credits_TilesCGBPal5c2 12575
#define Credits_TilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Credits_TilesCGBPal6c0 32767
#define Credits_TilesCGBPal6c1 24286
#define Credits_TilesCGBPal6c2 12575
#define Credits_TilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Credits_TilesCGBPal7c0 32767
#define Credits_TilesCGBPal7c1 24286
#define Credits_TilesCGBPal7c2 12575
#define Credits_TilesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char Credits_TilesCGB[];
/* Start of tile array. */
extern unsigned char Credits_Tiles[];

/* End of SRC/CREDITS_TILES.H */
