/*

 CREDITS_MAP.H

 Map Include File.

 Info:
   Section       : Map
   Bank          : 0
   Map size      : 20 x 208
   Tile set      : 15_Credits_Tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Credits_MapWidth 20
#define Credits_MapHeight 208
#define Credits_MapBank 0

#define Credits_Map Credits_MapPLN0
extern const unsigned char Credits_MapPLN0[];
extern const unsigned char Credits_MapPLN1[];

/* End of CREDITS_MAP.H */
