/*

 CREDITS_ANIM_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 63

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Credits_Anim_SpritesBank 0

/* Super Gameboy palette 0 */
#define Credits_Anim_SpritesSGBPal0c0 6076
#define Credits_Anim_SpritesSGBPal0c1 8935
#define Credits_Anim_SpritesSGBPal0c2 6596
#define Credits_Anim_SpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Credits_Anim_SpritesSGBPal1c0 6076
#define Credits_Anim_SpritesSGBPal1c1 8935
#define Credits_Anim_SpritesSGBPal1c2 6596
#define Credits_Anim_SpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Credits_Anim_SpritesSGBPal2c0 6076
#define Credits_Anim_SpritesSGBPal2c1 8935
#define Credits_Anim_SpritesSGBPal2c2 6596
#define Credits_Anim_SpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Credits_Anim_SpritesSGBPal3c0 6076
#define Credits_Anim_SpritesSGBPal3c1 8935
#define Credits_Anim_SpritesSGBPal3c2 6596
#define Credits_Anim_SpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Credits_Anim_SpritesCGBPal0c0 32767
#define Credits_Anim_SpritesCGBPal0c1 2911
#define Credits_Anim_SpritesCGBPal0c2 1224
#define Credits_Anim_SpritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Credits_Anim_SpritesCGBPal1c0 32767
#define Credits_Anim_SpritesCGBPal1c1 27520
#define Credits_Anim_SpritesCGBPal1c2 10282
#define Credits_Anim_SpritesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Credits_Anim_SpritesCGBPal2c0 0
#define Credits_Anim_SpritesCGBPal2c1 28606
#define Credits_Anim_SpritesCGBPal2c2 32117
#define Credits_Anim_SpritesCGBPal2c3 16426

/* Gameboy Color palette 3 */
#define Credits_Anim_SpritesCGBPal3c0 0
#define Credits_Anim_SpritesCGBPal3c1 12684
#define Credits_Anim_SpritesCGBPal3c2 21140
#define Credits_Anim_SpritesCGBPal3c3 32767

/* Gameboy Color palette 4 */
#define Credits_Anim_SpritesCGBPal4c0 0
#define Credits_Anim_SpritesCGBPal4c1 12684
#define Credits_Anim_SpritesCGBPal4c2 21140
#define Credits_Anim_SpritesCGBPal4c3 32767

/* Gameboy Color palette 5 */
#define Credits_Anim_SpritesCGBPal5c0 0
#define Credits_Anim_SpritesCGBPal5c1 12684
#define Credits_Anim_SpritesCGBPal5c2 21140
#define Credits_Anim_SpritesCGBPal5c3 32767

/* Gameboy Color palette 6 */
#define Credits_Anim_SpritesCGBPal6c0 0
#define Credits_Anim_SpritesCGBPal6c1 12684
#define Credits_Anim_SpritesCGBPal6c2 21140
#define Credits_Anim_SpritesCGBPal6c3 32767

/* Gameboy Color palette 7 */
#define Credits_Anim_SpritesCGBPal7c0 0
#define Credits_Anim_SpritesCGBPal7c1 12684
#define Credits_Anim_SpritesCGBPal7c2 21140
#define Credits_Anim_SpritesCGBPal7c3 32767
/* CGBpalette entries. */
extern const unsigned char Credits_Anim_SpritesCGB[];
/* Start of tile array. */
extern const unsigned char Credits_Anim_Sprites[];

/* End of CREDITS_ANIM_SPRITES.H */
