/*

 HOMER_MAP.H

 Map Include File.

 Info:
   Section       : Map
   Bank          : 0
   Map size      : 20 x 20
   Tile set      : 4_Homer_Tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Homer_MapWidth 20
#define Homer_MapHeight 20
#define Homer_MapBank 0

#define Homer_Map Homer_MapPLN0
extern const unsigned char Homer_MapPLN0[];
extern const unsigned char Homer_MapPLN1[];

/* End of HOMER_MAP.H */
