/*

 SRC/HOMER_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 40

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Homer_SpritesBank 0

/* Super Gameboy palette 0 */
#define Homer_SpritesSGBPal0c0 6076
#define Homer_SpritesSGBPal0c1 8935
#define Homer_SpritesSGBPal0c2 6596
#define Homer_SpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Homer_SpritesSGBPal1c0 6076
#define Homer_SpritesSGBPal1c1 8935
#define Homer_SpritesSGBPal1c2 6596
#define Homer_SpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Homer_SpritesSGBPal2c0 6076
#define Homer_SpritesSGBPal2c1 8935
#define Homer_SpritesSGBPal2c2 6596
#define Homer_SpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Homer_SpritesSGBPal3c0 6076
#define Homer_SpritesSGBPal3c1 8935
#define Homer_SpritesSGBPal3c2 6596
#define Homer_SpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Homer_SpritesCGBPal0c0 32265
#define Homer_SpritesCGBPal0c1 0
#define Homer_SpritesCGBPal0c2 2401
#define Homer_SpritesCGBPal0c3 10218

/* Gameboy Color palette 1 */
#define Homer_SpritesCGBPal1c0 32265
#define Homer_SpritesCGBPal1c1 32767
#define Homer_SpritesCGBPal1c2 12684
#define Homer_SpritesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Homer_SpritesCGBPal2c0 32265
#define Homer_SpritesCGBPal2c1 26815
#define Homer_SpritesCGBPal2c2 20500
#define Homer_SpritesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Homer_SpritesCGBPal3c0 0
#define Homer_SpritesCGBPal3c1 0
#define Homer_SpritesCGBPal3c2 0
#define Homer_SpritesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Homer_SpritesCGBPal4c0 0
#define Homer_SpritesCGBPal4c1 0
#define Homer_SpritesCGBPal4c2 0
#define Homer_SpritesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Homer_SpritesCGBPal5c0 0
#define Homer_SpritesCGBPal5c1 0
#define Homer_SpritesCGBPal5c2 0
#define Homer_SpritesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Homer_SpritesCGBPal6c0 0
#define Homer_SpritesCGBPal6c1 0
#define Homer_SpritesCGBPal6c2 0
#define Homer_SpritesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Homer_SpritesCGBPal7c0 0
#define Homer_SpritesCGBPal7c1 0
#define Homer_SpritesCGBPal7c2 0
#define Homer_SpritesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char Homer_SpritesCGB[];
/* Start of tile array. */
extern unsigned char Homer_Sprites[];

/* End of SRC/HOMER_SPRITES.H */
