/*

 HOMER_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 200

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Homer_TilesBank 0

/* Super Gameboy palette 0 */
#define Homer_TilesSGBPal0c0 6076
#define Homer_TilesSGBPal0c1 8935
#define Homer_TilesSGBPal0c2 6596
#define Homer_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Homer_TilesSGBPal1c0 6076
#define Homer_TilesSGBPal1c1 8935
#define Homer_TilesSGBPal1c2 6596
#define Homer_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Homer_TilesSGBPal2c0 6076
#define Homer_TilesSGBPal2c1 8935
#define Homer_TilesSGBPal2c2 6596
#define Homer_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Homer_TilesSGBPal3c0 6076
#define Homer_TilesSGBPal3c1 8935
#define Homer_TilesSGBPal3c2 6596
#define Homer_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Homer_TilesCGBPal0c0 29216
#define Homer_TilesCGBPal0c1 5856
#define Homer_TilesCGBPal0c2 1378
#define Homer_TilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Homer_TilesCGBPal1c0 29216
#define Homer_TilesCGBPal1c1 5856
#define Homer_TilesCGBPal1c2 32767
#define Homer_TilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Homer_TilesCGBPal2c0 29216
#define Homer_TilesCGBPal2c1 31197
#define Homer_TilesCGBPal2c2 26653
#define Homer_TilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Homer_TilesCGBPal3c0 29216
#define Homer_TilesCGBPal3c1 18078
#define Homer_TilesCGBPal3c2 92
#define Homer_TilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Homer_TilesCGBPal4c0 29216
#define Homer_TilesCGBPal4c1 5856
#define Homer_TilesCGBPal4c2 31816
#define Homer_TilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Homer_TilesCGBPal5c0 29216
#define Homer_TilesCGBPal5c1 275
#define Homer_TilesCGBPal5c2 2559
#define Homer_TilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Homer_TilesCGBPal6c0 29216
#define Homer_TilesCGBPal6c1 9983
#define Homer_TilesCGBPal6c2 275
#define Homer_TilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Homer_TilesCGBPal7c0 29216
#define Homer_TilesCGBPal7c1 31816
#define Homer_TilesCGBPal7c2 32767
#define Homer_TilesCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char Homer_TilesCGB[];
/* Start of tile array. */
extern const unsigned char Homer_Tiles[];

/* End of HOMER_TILES.H */
