/*

 SRC/INTRO_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 82
   Tile set      : 0_tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Intro_MapWidth 20
#define Intro_MapHeight 82
#define Intro_MapBank 0

#define Intro_Map Intro_MapPLN0
extern unsigned char Intro_MapPLN0[];
extern unsigned char Intro_MapPLN1[];

/* End of SRC/INTRO_MAP.H */
