/*

 INTRO_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 47

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Intro_TilesBank 0

/* Super Gameboy palette 0 */
#define Intro_TilesSGBPal0c0 6076
#define Intro_TilesSGBPal0c1 8935
#define Intro_TilesSGBPal0c2 6596
#define Intro_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Intro_TilesSGBPal1c0 6076
#define Intro_TilesSGBPal1c1 8935
#define Intro_TilesSGBPal1c2 6596
#define Intro_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Intro_TilesSGBPal2c0 6076
#define Intro_TilesSGBPal2c1 8935
#define Intro_TilesSGBPal2c2 6596
#define Intro_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Intro_TilesSGBPal3c0 6076
#define Intro_TilesSGBPal3c1 8935
#define Intro_TilesSGBPal3c2 6596
#define Intro_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Intro_TilesCGBPal0c0 2144
#define Intro_TilesCGBPal0c1 32765
#define Intro_TilesCGBPal0c2 31720
#define Intro_TilesCGBPal0c3 8231

/* Gameboy Color palette 1 */
#define Intro_TilesCGBPal1c0 2144
#define Intro_TilesCGBPal1c1 7135
#define Intro_TilesCGBPal1c2 4064
#define Intro_TilesCGBPal1c3 1194

/* Gameboy Color palette 2 */
#define Intro_TilesCGBPal2c0 26368
#define Intro_TilesCGBPal2c1 351
#define Intro_TilesCGBPal2c2 125
#define Intro_TilesCGBPal2c3 5216

/* Gameboy Color palette 3 */
#define Intro_TilesCGBPal3c0 2144
#define Intro_TilesCGBPal3c1 7135
#define Intro_TilesCGBPal3c2 4064
#define Intro_TilesCGBPal3c3 26592

/* Gameboy Color palette 4 */
#define Intro_TilesCGBPal4c0 8165
#define Intro_TilesCGBPal4c1 748
#define Intro_TilesCGBPal4c2 1539
#define Intro_TilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Intro_TilesCGBPal5c0 8165
#define Intro_TilesCGBPal5c1 748
#define Intro_TilesCGBPal5c2 1539
#define Intro_TilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Intro_TilesCGBPal6c0 8165
#define Intro_TilesCGBPal6c1 748
#define Intro_TilesCGBPal6c2 1539
#define Intro_TilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Intro_TilesCGBPal7c0 8165
#define Intro_TilesCGBPal7c1 748
#define Intro_TilesCGBPal7c2 1539
#define Intro_TilesCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char Intro_TilesCGB[];
/* Start of tile array. */
extern const unsigned char Intro_Tiles[];

/* End of INTRO_TILES.H */
