/*

 LISA_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 4 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Lisa_TilesBank 0

/* Super Gameboy palette 0 */
#define Lisa_TilesSGBPal0c0 6076
#define Lisa_TilesSGBPal0c1 8935
#define Lisa_TilesSGBPal0c2 6596
#define Lisa_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Lisa_TilesSGBPal1c0 6076
#define Lisa_TilesSGBPal1c1 8935
#define Lisa_TilesSGBPal1c2 6596
#define Lisa_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Lisa_TilesSGBPal2c0 6076
#define Lisa_TilesSGBPal2c1 8935
#define Lisa_TilesSGBPal2c2 6596
#define Lisa_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Lisa_TilesSGBPal3c0 6076
#define Lisa_TilesSGBPal3c1 8935
#define Lisa_TilesSGBPal3c2 6596
#define Lisa_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Lisa_TilesCGBPal0c0 32101
#define Lisa_TilesCGBPal0c1 8165
#define Lisa_TilesCGBPal0c2 32767
#define Lisa_TilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Lisa_TilesCGBPal1c0 32101
#define Lisa_TilesCGBPal1c1 5093
#define Lisa_TilesCGBPal1c2 5569
#define Lisa_TilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Lisa_TilesCGBPal2c0 9183
#define Lisa_TilesCGBPal2c1 5093
#define Lisa_TilesCGBPal2c2 5569
#define Lisa_TilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Lisa_TilesCGBPal3c0 32767
#define Lisa_TilesCGBPal3c1 5093
#define Lisa_TilesCGBPal3c2 5569
#define Lisa_TilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Lisa_TilesCGBPal4c0 22556
#define Lisa_TilesCGBPal4c1 5093
#define Lisa_TilesCGBPal4c2 5569
#define Lisa_TilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Lisa_TilesCGBPal5c0 8799
#define Lisa_TilesCGBPal5c1 5093
#define Lisa_TilesCGBPal5c2 5569
#define Lisa_TilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Lisa_TilesCGBPal6c0 15871
#define Lisa_TilesCGBPal6c1 31
#define Lisa_TilesCGBPal6c2 5569
#define Lisa_TilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Lisa_TilesCGBPal7c0 22556
#define Lisa_TilesCGBPal7c1 8165
#define Lisa_TilesCGBPal7c2 32767
#define Lisa_TilesCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char Lisa_TilesCGB[];
/* Start of tile array. */
extern const unsigned char Lisa_Tiles[];

/* End of LISA_TILES.H */
