/*

 SRC/LISA_MAP.H

 Map Include File.

 Info:
   Section       : Map
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : 7_lisa.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Lisa_MapWidth 20
#define Lisa_MapHeight 18
#define Lisa_MapBank 0

#define Lisa_Map Lisa_MapPLN0
extern unsigned char Lisa_MapPLN0[];
extern unsigned char Lisa_MapPLN1[];

/* End of SRC/LISA_MAP.H */
