/*

 PARALLAX_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 39

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Parallax_SpritesBank 0

/* Super Gameboy palette 0 */
#define Parallax_SpritesSGBPal0c0 6076
#define Parallax_SpritesSGBPal0c1 8935
#define Parallax_SpritesSGBPal0c2 6596
#define Parallax_SpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Parallax_SpritesSGBPal1c0 6076
#define Parallax_SpritesSGBPal1c1 8935
#define Parallax_SpritesSGBPal1c2 6596
#define Parallax_SpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Parallax_SpritesSGBPal2c0 6076
#define Parallax_SpritesSGBPal2c1 8935
#define Parallax_SpritesSGBPal2c2 6596
#define Parallax_SpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Parallax_SpritesSGBPal3c0 6076
#define Parallax_SpritesSGBPal3c1 8935
#define Parallax_SpritesSGBPal3c2 6596
#define Parallax_SpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Parallax_SpritesCGBPal0c0 21280
#define Parallax_SpritesCGBPal0c1 32767
#define Parallax_SpritesCGBPal0c2 186
#define Parallax_SpritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Parallax_SpritesCGBPal1c0 21280
#define Parallax_SpritesCGBPal1c1 32767
#define Parallax_SpritesCGBPal1c2 29504
#define Parallax_SpritesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Parallax_SpritesCGBPal2c0 21280
#define Parallax_SpritesCGBPal2c1 21140
#define Parallax_SpritesCGBPal2c2 186
#define Parallax_SpritesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Parallax_SpritesCGBPal3c0 21280
#define Parallax_SpritesCGBPal3c1 21140
#define Parallax_SpritesCGBPal3c2 28625
#define Parallax_SpritesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Parallax_SpritesCGBPal4c0 21280
#define Parallax_SpritesCGBPal4c1 24552
#define Parallax_SpritesCGBPal4c2 32389
#define Parallax_SpritesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Parallax_SpritesCGBPal5c0 21280
#define Parallax_SpritesCGBPal5c1 18302
#define Parallax_SpritesCGBPal5c2 669
#define Parallax_SpritesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Parallax_SpritesCGBPal6c0 21280
#define Parallax_SpritesCGBPal6c1 32389
#define Parallax_SpritesCGBPal6c2 11904
#define Parallax_SpritesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Parallax_SpritesCGBPal7c0 21280
#define Parallax_SpritesCGBPal7c1 24552
#define Parallax_SpritesCGBPal7c2 23254
#define Parallax_SpritesCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char Parallax_SpritesCGB[];
/* Start of tile array. */
extern const unsigned char Parallax_Sprites[];

/* End of PARALLAX_SPRITES.H */
