/*

 PARALLAX_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 81

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Parallax_TilesBank 0

/* Super Gameboy palette 0 */
#define Parallax_TilesSGBPal0c0 6076
#define Parallax_TilesSGBPal0c1 8935
#define Parallax_TilesSGBPal0c2 6596
#define Parallax_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Parallax_TilesSGBPal1c0 6076
#define Parallax_TilesSGBPal1c1 8935
#define Parallax_TilesSGBPal1c2 6596
#define Parallax_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Parallax_TilesSGBPal2c0 6076
#define Parallax_TilesSGBPal2c1 8935
#define Parallax_TilesSGBPal2c2 6596
#define Parallax_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Parallax_TilesSGBPal3c0 6076
#define Parallax_TilesSGBPal3c1 8935
#define Parallax_TilesSGBPal3c2 6596
#define Parallax_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Parallax_TilesCGBPal0c0 31973
#define Parallax_TilesCGBPal0c1 32767
#define Parallax_TilesCGBPal0c2 23254
#define Parallax_TilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Parallax_TilesCGBPal1c0 32736
#define Parallax_TilesCGBPal1c1 746
#define Parallax_TilesCGBPal1c2 1443
#define Parallax_TilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Parallax_TilesCGBPal2c0 32767
#define Parallax_TilesCGBPal2c1 8166
#define Parallax_TilesCGBPal2c2 1473
#define Parallax_TilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Parallax_TilesCGBPal3c0 32767
#define Parallax_TilesCGBPal3c1 12127
#define Parallax_TilesCGBPal3c2 1328
#define Parallax_TilesCGBPal3c3 1024

/* Gameboy Color palette 4 */
#define Parallax_TilesCGBPal4c0 23552
#define Parallax_TilesCGBPal4c1 4094
#define Parallax_TilesCGBPal4c2 1443
#define Parallax_TilesCGBPal4c3 31707

/* Gameboy Color palette 5 */
#define Parallax_TilesCGBPal5c0 32767
#define Parallax_TilesCGBPal5c1 31836
#define Parallax_TilesCGBPal5c2 19473
#define Parallax_TilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Parallax_TilesCGBPal6c0 32767
#define Parallax_TilesCGBPal6c1 31646
#define Parallax_TilesCGBPal6c2 31836
#define Parallax_TilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Parallax_TilesCGBPal7c0 32767
#define Parallax_TilesCGBPal7c1 23454
#define Parallax_TilesCGBPal7c2 189
#define Parallax_TilesCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char Parallax_TilesCGB[];
/* Start of tile array. */
extern const unsigned char Parallax_Tiles[];

/* End of PARALLAX_TILES.H */
