/*

 PARALLAX_ANIM.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 680

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Parallax_AnimBank 0

/* Super Gameboy palette 0 */
#define Parallax_AnimSGBPal0c0 6076
#define Parallax_AnimSGBPal0c1 8935
#define Parallax_AnimSGBPal0c2 6596
#define Parallax_AnimSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Parallax_AnimSGBPal1c0 6076
#define Parallax_AnimSGBPal1c1 8935
#define Parallax_AnimSGBPal1c2 6596
#define Parallax_AnimSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Parallax_AnimSGBPal2c0 6076
#define Parallax_AnimSGBPal2c1 8935
#define Parallax_AnimSGBPal2c2 6596
#define Parallax_AnimSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Parallax_AnimSGBPal3c0 6076
#define Parallax_AnimSGBPal3c1 8935
#define Parallax_AnimSGBPal3c2 6596
#define Parallax_AnimSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Parallax_AnimCGBPal0c0 32070
#define Parallax_AnimCGBPal0c1 32767
#define Parallax_AnimCGBPal0c2 23254
#define Parallax_AnimCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Parallax_AnimCGBPal1c0 32070
#define Parallax_AnimCGBPal1c1 746
#define Parallax_AnimCGBPal1c2 1443
#define Parallax_AnimCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Parallax_AnimCGBPal2c0 32767
#define Parallax_AnimCGBPal2c1 8166
#define Parallax_AnimCGBPal2c2 1473
#define Parallax_AnimCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Parallax_AnimCGBPal3c0 32767
#define Parallax_AnimCGBPal3c1 12127
#define Parallax_AnimCGBPal3c2 1328
#define Parallax_AnimCGBPal3c3 1024

/* Gameboy Color palette 4 */
#define Parallax_AnimCGBPal4c0 14372
#define Parallax_AnimCGBPal4c1 4094
#define Parallax_AnimCGBPal4c2 1443
#define Parallax_AnimCGBPal4c3 31707

/* Gameboy Color palette 5 */
#define Parallax_AnimCGBPal5c0 32767
#define Parallax_AnimCGBPal5c1 31836
#define Parallax_AnimCGBPal5c2 19473
#define Parallax_AnimCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Parallax_AnimCGBPal6c0 32767
#define Parallax_AnimCGBPal6c1 31646
#define Parallax_AnimCGBPal6c2 31836
#define Parallax_AnimCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Parallax_AnimCGBPal7c0 32767
#define Parallax_AnimCGBPal7c1 23454
#define Parallax_AnimCGBPal7c2 189
#define Parallax_AnimCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char Parallax_AnimCGB[];
/* Start of tile array. */
extern const unsigned char Parallax_Anim[];

/* End of PARALLAX_ANIM.H */
