/*

 SRC/PERSP3DCLOUDS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 14

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Persp3DCloudsBank 0

/* Super Gameboy palette 0 */
#define Persp3DCloudsSGBPal0c0 6076
#define Persp3DCloudsSGBPal0c1 8935
#define Persp3DCloudsSGBPal0c2 6596
#define Persp3DCloudsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Persp3DCloudsSGBPal1c0 6076
#define Persp3DCloudsSGBPal1c1 8935
#define Persp3DCloudsSGBPal1c2 6596
#define Persp3DCloudsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Persp3DCloudsSGBPal2c0 6076
#define Persp3DCloudsSGBPal2c1 8935
#define Persp3DCloudsSGBPal2c2 6596
#define Persp3DCloudsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Persp3DCloudsSGBPal3c0 6076
#define Persp3DCloudsSGBPal3c1 8935
#define Persp3DCloudsSGBPal3c2 6596
#define Persp3DCloudsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Persp3DCloudsCGBPal0c0 32267
#define Persp3DCloudsCGBPal0c1 32767
#define Persp3DCloudsCGBPal0c2 21008
#define Persp3DCloudsCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Persp3DCloudsCGBPal1c0 15313
#define Persp3DCloudsCGBPal1c1 998
#define Persp3DCloudsCGBPal1c2 3680
#define Persp3DCloudsCGBPal1c3 1185

/* Gameboy Color palette 2 */
#define Persp3DCloudsCGBPal2c0 7673
#define Persp3DCloudsCGBPal2c1 7405
#define Persp3DCloudsCGBPal2c2 3680
#define Persp3DCloudsCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Persp3DCloudsCGBPal3c0 32267
#define Persp3DCloudsCGBPal3c1 18384
#define Persp3DCloudsCGBPal3c2 1760
#define Persp3DCloudsCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Persp3DCloudsCGBPal4c0 17395
#define Persp3DCloudsCGBPal4c1 998
#define Persp3DCloudsCGBPal4c2 8640
#define Persp3DCloudsCGBPal4c3 1185

/* Gameboy Color palette 5 */
#define Persp3DCloudsCGBPal5c0 32767
#define Persp3DCloudsCGBPal5c1 32267
#define Persp3DCloudsCGBPal5c2 20158
#define Persp3DCloudsCGBPal5c3 31

/* Gameboy Color palette 6 */
#define Persp3DCloudsCGBPal6c0 32767
#define Persp3DCloudsCGBPal6c1 22197
#define Persp3DCloudsCGBPal6c2 11627
#define Persp3DCloudsCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Persp3DCloudsCGBPal7c0 5219
#define Persp3DCloudsCGBPal7c1 10504
#define Persp3DCloudsCGBPal7c2 16846
#define Persp3DCloudsCGBPal7c3 5153
/* CGBpalette entries. */
extern const unsigned char Persp3DCloudsCGB[];
/* Start of tile array. */
extern const unsigned char Persp3DClouds[];

/* End of SRC/PERSP3DCLOUDS.H */
