/*

 PERSP3DMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : 2_P3D_Tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Persp3DMapWidth 32
#define Persp3DMapHeight 18
#define Persp3DMapBank 0

#define Persp3DMap Persp3DMapPLN0
extern const unsigned char Persp3DMapPLN0[];
extern const unsigned char Persp3DMapPLN1[];

/* End of PERSP3DMAP.H */
