/*

 PERSP3DTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 342

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Persp3DTilesBank 0

/* Super Gameboy palette 0 */
#define Persp3DTilesSGBPal0c0 6076
#define Persp3DTilesSGBPal0c1 8935
#define Persp3DTilesSGBPal0c2 6596
#define Persp3DTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Persp3DTilesSGBPal1c0 6076
#define Persp3DTilesSGBPal1c1 8935
#define Persp3DTilesSGBPal1c2 6596
#define Persp3DTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Persp3DTilesSGBPal2c0 6076
#define Persp3DTilesSGBPal2c1 8935
#define Persp3DTilesSGBPal2c2 6596
#define Persp3DTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Persp3DTilesSGBPal3c0 6076
#define Persp3DTilesSGBPal3c1 8935
#define Persp3DTilesSGBPal3c2 6596
#define Persp3DTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Persp3DTilesCGBPal0c0 32267
#define Persp3DTilesCGBPal0c1 30430
#define Persp3DTilesCGBPal0c2 21530
#define Persp3DTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Persp3DTilesCGBPal1c0 15313
#define Persp3DTilesCGBPal1c1 998
#define Persp3DTilesCGBPal1c2 3680
#define Persp3DTilesCGBPal1c3 1185

/* Gameboy Color palette 2 */
#define Persp3DTilesCGBPal2c0 7673
#define Persp3DTilesCGBPal2c1 7405
#define Persp3DTilesCGBPal2c2 3680
#define Persp3DTilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Persp3DTilesCGBPal3c0 32267
#define Persp3DTilesCGBPal3c1 18384
#define Persp3DTilesCGBPal3c2 1760
#define Persp3DTilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Persp3DTilesCGBPal4c0 17395
#define Persp3DTilesCGBPal4c1 998
#define Persp3DTilesCGBPal4c2 8640
#define Persp3DTilesCGBPal4c3 1185

/* Gameboy Color palette 5 */
#define Persp3DTilesCGBPal5c0 32767
#define Persp3DTilesCGBPal5c1 32267
#define Persp3DTilesCGBPal5c2 20158
#define Persp3DTilesCGBPal5c3 31

/* Gameboy Color palette 6 */
#define Persp3DTilesCGBPal6c0 5219
#define Persp3DTilesCGBPal6c1 10504
#define Persp3DTilesCGBPal6c2 16846
#define Persp3DTilesCGBPal6c3 5153

/* Gameboy Color palette 7 */
#define Persp3DTilesCGBPal7c0 10570
#define Persp3DTilesCGBPal7c1 23254
#define Persp3DTilesCGBPal7c2 32767
#define Persp3DTilesCGBPal7c3 5153
/* CGBpalette entries. */
extern const unsigned char Persp3DTilesCGB[];
/* Start of tile array. */
extern const unsigned char Persp3DTilesBLK0[];
/* Start of tile array. */
extern const unsigned char Persp3DTilesBLK1[];

/* End of PERSP3DTILES.H */
