/*

 SRC/PLASMA_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : 11_Plasma_Tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Plasma_MapWidth 32
#define Plasma_MapHeight 18
#define Plasma_MapBank 0

#define Plasma_Map Plasma_MapPLN0
extern unsigned char Plasma_MapPLN0[];
extern unsigned char Plasma_MapPLN1[];

/* End of SRC/PLASMA_MAP.H */
