/*

 PLASMA_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 32

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Plasma_TilesBank 0

/* Super Gameboy palette 0 */
#define Plasma_TilesSGBPal0c0 6076
#define Plasma_TilesSGBPal0c1 8935
#define Plasma_TilesSGBPal0c2 6596
#define Plasma_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Plasma_TilesSGBPal1c0 6076
#define Plasma_TilesSGBPal1c1 8935
#define Plasma_TilesSGBPal1c2 6596
#define Plasma_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Plasma_TilesSGBPal2c0 6076
#define Plasma_TilesSGBPal2c1 8935
#define Plasma_TilesSGBPal2c2 6596
#define Plasma_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Plasma_TilesSGBPal3c0 6076
#define Plasma_TilesSGBPal3c1 8935
#define Plasma_TilesSGBPal3c2 6596
#define Plasma_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Plasma_TilesCGBPal0c0 1249
#define Plasma_TilesCGBPal0c1 4640
#define Plasma_TilesCGBPal0c2 14320
#define Plasma_TilesCGBPal0c3 1249

/* Gameboy Color palette 1 */
#define Plasma_TilesCGBPal1c0 1249
#define Plasma_TilesCGBPal1c1 4640
#define Plasma_TilesCGBPal1c2 6141
#define Plasma_TilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Plasma_TilesCGBPal2c0 1249
#define Plasma_TilesCGBPal2c1 4640
#define Plasma_TilesCGBPal2c2 31480
#define Plasma_TilesCGBPal2c3 25600

/* Gameboy Color palette 3 */
#define Plasma_TilesCGBPal3c0 1249
#define Plasma_TilesCGBPal3c1 4640
#define Plasma_TilesCGBPal3c2 18046
#define Plasma_TilesCGBPal3c3 8218

/* Gameboy Color palette 4 */
#define Plasma_TilesCGBPal4c0 1249
#define Plasma_TilesCGBPal4c1 14320
#define Plasma_TilesCGBPal4c2 9513
#define Plasma_TilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Plasma_TilesCGBPal5c0 1249
#define Plasma_TilesCGBPal5c1 4640
#define Plasma_TilesCGBPal5c2 9513
#define Plasma_TilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Plasma_TilesCGBPal6c0 1249
#define Plasma_TilesCGBPal6c1 4640
#define Plasma_TilesCGBPal6c2 9513
#define Plasma_TilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Plasma_TilesCGBPal7c0 1249
#define Plasma_TilesCGBPal7c1 9513
#define Plasma_TilesCGBPal7c2 32767
#define Plasma_TilesCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char Plasma_TilesCGB[];
/* Start of tile array. */
extern const unsigned char Plasma_Tiles[];

/* End of PLASMA_TILES.H */
