/*

 SRC/ROAD3DSPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 23

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Road3DspritesBank 0

/* Super Gameboy palette 0 */
#define Road3DspritesSGBPal0c0 6076
#define Road3DspritesSGBPal0c1 8935
#define Road3DspritesSGBPal0c2 6596
#define Road3DspritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Road3DspritesSGBPal1c0 6076
#define Road3DspritesSGBPal1c1 8935
#define Road3DspritesSGBPal1c2 6596
#define Road3DspritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Road3DspritesSGBPal2c0 6076
#define Road3DspritesSGBPal2c1 8935
#define Road3DspritesSGBPal2c2 6596
#define Road3DspritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Road3DspritesSGBPal3c0 6076
#define Road3DspritesSGBPal3c1 8935
#define Road3DspritesSGBPal3c2 6596
#define Road3DspritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Road3DspritesCGBPal0c0 32767
#define Road3DspritesCGBPal0c1 32767
#define Road3DspritesCGBPal0c2 29725
#define Road3DspritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Road3DspritesCGBPal1c0 32767
#define Road3DspritesCGBPal1c1 32767
#define Road3DspritesCGBPal1c2 29725
#define Road3DspritesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Road3DspritesCGBPal2c0 32767
#define Road3DspritesCGBPal2c1 21140
#define Road3DspritesCGBPal2c2 29725
#define Road3DspritesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Road3DspritesCGBPal3c0 32767
#define Road3DspritesCGBPal3c1 32619
#define Road3DspritesCGBPal3c2 29725
#define Road3DspritesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Road3DspritesCGBPal4c0 32767
#define Road3DspritesCGBPal4c1 9213
#define Road3DspritesCGBPal4c2 278
#define Road3DspritesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Road3DspritesCGBPal5c0 32767
#define Road3DspritesCGBPal5c1 31741
#define Road3DspritesCGBPal5c2 32352
#define Road3DspritesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Road3DspritesCGBPal6c0 31536
#define Road3DspritesCGBPal6c1 30240
#define Road3DspritesCGBPal6c2 32767
#define Road3DspritesCGBPal6c3 801

/* Gameboy Color palette 7 */
#define Road3DspritesCGBPal7c0 0
#define Road3DspritesCGBPal7c1 0
#define Road3DspritesCGBPal7c2 32767
#define Road3DspritesCGBPal7c3 16912
/* CGBpalette entries. */
extern unsigned char Road3DspritesCGB[];
/* Start of tile array. */
extern unsigned char Road3Dsprites[];

/* End of SRC/ROAD3DSPRITES.H */
