/*

 SRC/ROADFMAP3D.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 6
   Tile set      : 3_roadmap.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define RoadFMap3DWidth 20
#define RoadFMap3DHeight 6
#define RoadFMap3DBank 0

#define RoadFMap3D RoadFMap3DPLN0
extern unsigned char RoadFMap3DPLN0[];
extern unsigned char RoadFMap3DPLN1[];

/* End of SRC/ROADFMAP3D.H */
