/*

 SRC/ROADBKGMAP3D.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : 3_roadmap.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define RoadBKGMap3DWidth 32
#define RoadBKGMap3DHeight 18
#define RoadBKGMap3DBank 0

#define RoadBKGMap3D RoadBKGMap3DPLN0
extern unsigned char RoadBKGMap3DPLN0[];
extern unsigned char RoadBKGMap3DPLN1[];

/* End of SRC/ROADBKGMAP3D.H */
