/*

 SRC/ROAD3DTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 79

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Road3DTilesBank 0

/* Super Gameboy palette 0 */
#define Road3DTilesSGBPal0c0 6076
#define Road3DTilesSGBPal0c1 8935
#define Road3DTilesSGBPal0c2 6596
#define Road3DTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Road3DTilesSGBPal1c0 6076
#define Road3DTilesSGBPal1c1 8935
#define Road3DTilesSGBPal1c2 6596
#define Road3DTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Road3DTilesSGBPal2c0 6076
#define Road3DTilesSGBPal2c1 8935
#define Road3DTilesSGBPal2c2 6596
#define Road3DTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Road3DTilesSGBPal3c0 6076
#define Road3DTilesSGBPal3c1 8935
#define Road3DTilesSGBPal3c2 6596
#define Road3DTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Road3DTilesCGBPal0c0 31536
#define Road3DTilesCGBPal0c1 30240
#define Road3DTilesCGBPal0c2 32767
#define Road3DTilesCGBPal0c3 801

/* Gameboy Color palette 1 */
#define Road3DTilesCGBPal1c0 17362
#define Road3DTilesCGBPal1c1 833
#define Road3DTilesCGBPal1c2 611
#define Road3DTilesCGBPal1c3 16912

/* Gameboy Color palette 2 */
#define Road3DTilesCGBPal2c0 32767
#define Road3DTilesCGBPal2c1 17362
#define Road3DTilesCGBPal2c2 833
#define Road3DTilesCGBPal2c3 16912

/* Gameboy Color palette 3 */
#define Road3DTilesCGBPal3c0 31536
#define Road3DTilesCGBPal3c1 15339
#define Road3DTilesCGBPal3c2 6752
#define Road3DTilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Road3DTilesCGBPal4c0 7165
#define Road3DTilesCGBPal4c1 15339
#define Road3DTilesCGBPal4c2 6752
#define Road3DTilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Road3DTilesCGBPal5c0 7165
#define Road3DTilesCGBPal5c1 31909
#define Road3DTilesCGBPal5c2 31644
#define Road3DTilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Road3DTilesCGBPal6c0 26425
#define Road3DTilesCGBPal6c1 15339
#define Road3DTilesCGBPal6c2 6752
#define Road3DTilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Road3DTilesCGBPal7c0 0
#define Road3DTilesCGBPal7c1 0
#define Road3DTilesCGBPal7c2 32767
#define Road3DTilesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char Road3DTilesCGB[];
/* Start of tile array. */
extern unsigned char Road3DTiles[];

/* End of SRC/ROAD3DTILES.H */
