/*

 SRC/ROTO_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 64

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Roto_TilesBank 0

/* Super Gameboy palette 0 */
#define Roto_TilesSGBPal0c0 6076
#define Roto_TilesSGBPal0c1 8935
#define Roto_TilesSGBPal0c2 6596
#define Roto_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Roto_TilesSGBPal1c0 6076
#define Roto_TilesSGBPal1c1 8935
#define Roto_TilesSGBPal1c2 6596
#define Roto_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Roto_TilesSGBPal2c0 6076
#define Roto_TilesSGBPal2c1 8935
#define Roto_TilesSGBPal2c2 6596
#define Roto_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Roto_TilesSGBPal3c0 6076
#define Roto_TilesSGBPal3c1 8935
#define Roto_TilesSGBPal3c2 6596
#define Roto_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Roto_TilesCGBPal0c0 5631
#define Roto_TilesCGBPal0c1 11040
#define Roto_TilesCGBPal0c2 3071
#define Roto_TilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Roto_TilesCGBPal1c0 32733
#define Roto_TilesCGBPal1c1 11040
#define Roto_TilesCGBPal1c2 3071
#define Roto_TilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Roto_TilesCGBPal2c0 31444
#define Roto_TilesCGBPal2c1 11040
#define Roto_TilesCGBPal2c2 3071
#define Roto_TilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Roto_TilesCGBPal3c0 31182
#define Roto_TilesCGBPal3c1 11040
#define Roto_TilesCGBPal3c2 3071
#define Roto_TilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Roto_TilesCGBPal4c0 32008
#define Roto_TilesCGBPal4c1 11040
#define Roto_TilesCGBPal4c2 3071
#define Roto_TilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Roto_TilesCGBPal5c0 31749
#define Roto_TilesCGBPal5c1 11040
#define Roto_TilesCGBPal5c2 3071
#define Roto_TilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Roto_TilesCGBPal6c0 23553
#define Roto_TilesCGBPal6c1 11040
#define Roto_TilesCGBPal6c2 3071
#define Roto_TilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Roto_TilesCGBPal7c0 16419
#define Roto_TilesCGBPal7c1 11040
#define Roto_TilesCGBPal7c2 3071
#define Roto_TilesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char Roto_TilesCGB[];
/* Start of tile array. */
extern unsigned char Roto_Tiles[];

/* End of SRC/ROTO_TILES.H */
