/*

 SRC/ROTO_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : 10_Roto_Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Roto_MapWidth 20
#define Roto_MapHeight 18
#define Roto_MapBank 0

extern unsigned char Roto_Map[];

/* End of SRC/ROTO_MAP.H */
