/*

 SRC/SEA_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 20

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Sea_SpritesBank 0

/* Super Gameboy palette 0 */
#define Sea_SpritesSGBPal0c0 6076
#define Sea_SpritesSGBPal0c1 8935
#define Sea_SpritesSGBPal0c2 6596
#define Sea_SpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Sea_SpritesSGBPal1c0 6076
#define Sea_SpritesSGBPal1c1 8935
#define Sea_SpritesSGBPal1c2 6596
#define Sea_SpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Sea_SpritesSGBPal2c0 6076
#define Sea_SpritesSGBPal2c1 8935
#define Sea_SpritesSGBPal2c2 6596
#define Sea_SpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Sea_SpritesSGBPal3c0 6076
#define Sea_SpritesSGBPal3c1 8935
#define Sea_SpritesSGBPal3c2 6596
#define Sea_SpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Sea_SpritesCGBPal0c0 32265
#define Sea_SpritesCGBPal0c1 32765
#define Sea_SpritesCGBPal0c2 32742
#define Sea_SpritesCGBPal0c3 3048

/* Gameboy Color palette 1 */
#define Sea_SpritesCGBPal1c0 32265
#define Sea_SpritesCGBPal1c1 32767
#define Sea_SpritesCGBPal1c2 223
#define Sea_SpritesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Sea_SpritesCGBPal2c0 32265
#define Sea_SpritesCGBPal2c1 3070
#define Sea_SpritesCGBPal2c2 31744
#define Sea_SpritesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Sea_SpritesCGBPal3c0 32265
#define Sea_SpritesCGBPal3c1 32767
#define Sea_SpritesCGBPal3c2 31744
#define Sea_SpritesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Sea_SpritesCGBPal4c0 0
#define Sea_SpritesCGBPal4c1 0
#define Sea_SpritesCGBPal4c2 0
#define Sea_SpritesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Sea_SpritesCGBPal5c0 0
#define Sea_SpritesCGBPal5c1 0
#define Sea_SpritesCGBPal5c2 0
#define Sea_SpritesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Sea_SpritesCGBPal6c0 0
#define Sea_SpritesCGBPal6c1 0
#define Sea_SpritesCGBPal6c2 0
#define Sea_SpritesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Sea_SpritesCGBPal7c0 0
#define Sea_SpritesCGBPal7c1 0
#define Sea_SpritesCGBPal7c2 0
#define Sea_SpritesCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char Sea_SpritesCGB[];
/* Start of tile array. */
extern const unsigned char Sea_Sprites[];

/* End of SRC/SEA_SPRITES.H */
