/*

 SEA_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 31

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Sea_TilesBank 0

/* Super Gameboy palette 0 */
#define Sea_TilesSGBPal0c0 6076
#define Sea_TilesSGBPal0c1 8935
#define Sea_TilesSGBPal0c2 6596
#define Sea_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Sea_TilesSGBPal1c0 6076
#define Sea_TilesSGBPal1c1 8935
#define Sea_TilesSGBPal1c2 6596
#define Sea_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Sea_TilesSGBPal2c0 6076
#define Sea_TilesSGBPal2c1 8935
#define Sea_TilesSGBPal2c2 6596
#define Sea_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Sea_TilesSGBPal3c0 6076
#define Sea_TilesSGBPal3c1 8935
#define Sea_TilesSGBPal3c2 6596
#define Sea_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Sea_TilesCGBPal0c0 31537
#define Sea_TilesCGBPal0c1 9190
#define Sea_TilesCGBPal0c2 4640
#define Sea_TilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Sea_TilesCGBPal1c0 4640
#define Sea_TilesCGBPal1c1 9190
#define Sea_TilesCGBPal1c2 32642
#define Sea_TilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Sea_TilesCGBPal2c0 30216
#define Sea_TilesCGBPal2c1 9190
#define Sea_TilesCGBPal2c2 4640
#define Sea_TilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Sea_TilesCGBPal3c0 30086
#define Sea_TilesCGBPal3c1 9190
#define Sea_TilesCGBPal3c2 4640
#define Sea_TilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Sea_TilesCGBPal4c0 29956
#define Sea_TilesCGBPal4c1 9190
#define Sea_TilesCGBPal4c2 4640
#define Sea_TilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Sea_TilesCGBPal5c0 29826
#define Sea_TilesCGBPal5c1 9190
#define Sea_TilesCGBPal5c2 4640
#define Sea_TilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Sea_TilesCGBPal6c0 29760
#define Sea_TilesCGBPal6c1 9190
#define Sea_TilesCGBPal6c2 4640
#define Sea_TilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Sea_TilesCGBPal7c0 4640
#define Sea_TilesCGBPal7c1 9190
#define Sea_TilesCGBPal7c2 32395
#define Sea_TilesCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char Sea_TilesCGB[];
/* Start of tile array. */
extern const unsigned char Sea_Tiles[];

/* End of SEA_TILES.H */
