/*

 SRC/SEA_MAP.H

 Map Include File.

 Info:
   Section       : Map
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : 8_Sea_Tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Sea_MapWidth 32
#define Sea_MapHeight 18
#define Sea_MapBank 0

#define Sea_Map Sea_MapPLN0
extern unsigned char Sea_MapPLN0[];
extern unsigned char Sea_MapPLN1[];

/* End of SRC/SEA_MAP.H */
