/*

 SRC/TOWER_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : 9_tiles_tower.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Tower_MapWidth 20
#define Tower_MapHeight 18
#define Tower_MapBank 0

#define Tower_Map Tower_MapPLN0
extern const unsigned char Tower_MapPLN0[];
extern const unsigned char Tower_MapPLN1[];

/* End of SRC/TOWER_MAP.H */
