/*

 SRC/TOWER_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Tower_TilesBank 0

/* Super Gameboy palette 0 */
#define Tower_TilesSGBPal0c0 6076
#define Tower_TilesSGBPal0c1 8935
#define Tower_TilesSGBPal0c2 6596
#define Tower_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Tower_TilesSGBPal1c0 6076
#define Tower_TilesSGBPal1c1 8935
#define Tower_TilesSGBPal1c2 6596
#define Tower_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Tower_TilesSGBPal2c0 6076
#define Tower_TilesSGBPal2c1 8935
#define Tower_TilesSGBPal2c2 6596
#define Tower_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Tower_TilesSGBPal3c0 6076
#define Tower_TilesSGBPal3c1 8935
#define Tower_TilesSGBPal3c2 6596
#define Tower_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Tower_TilesCGBPal0c0 32175
#define Tower_TilesCGBPal0c1 31850
#define Tower_TilesCGBPal0c2 20488
#define Tower_TilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Tower_TilesCGBPal1c0 32767
#define Tower_TilesCGBPal1c1 9190
#define Tower_TilesCGBPal1c2 1568
#define Tower_TilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Tower_TilesCGBPal2c0 32767
#define Tower_TilesCGBPal2c1 9190
#define Tower_TilesCGBPal2c2 1568
#define Tower_TilesCGBPal2c3 1156

/* Gameboy Color palette 3 */
#define Tower_TilesCGBPal3c0 32767
#define Tower_TilesCGBPal3c1 9190
#define Tower_TilesCGBPal3c2 1568
#define Tower_TilesCGBPal3c3 2246

/* Gameboy Color palette 4 */
#define Tower_TilesCGBPal4c0 32767
#define Tower_TilesCGBPal4c1 9190
#define Tower_TilesCGBPal4c2 1568
#define Tower_TilesCGBPal4c3 1153

/* Gameboy Color palette 5 */
#define Tower_TilesCGBPal5c0 32767
#define Tower_TilesCGBPal5c1 9190
#define Tower_TilesCGBPal5c2 1568
#define Tower_TilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Tower_TilesCGBPal6c0 32009
#define Tower_TilesCGBPal6c1 31748
#define Tower_TilesCGBPal6c2 8225
#define Tower_TilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Tower_TilesCGBPal7c0 23574
#define Tower_TilesCGBPal7c1 30174
#define Tower_TilesCGBPal7c2 26628
#define Tower_TilesCGBPal7c3 5154
/* CGBpalette entries. */
extern unsigned char Tower_TilesCGB[];
/* Start of tile array. */
extern unsigned char Tower_Tiles[];

/* End of SRC/TOWER_TILES.H */
