/*

 SRC/TOWER_ANIM_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 239

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tower_anim_tilesBank 0

/* Super Gameboy palette 0 */
#define tower_anim_tilesSGBPal0c0 6076
#define tower_anim_tilesSGBPal0c1 8935
#define tower_anim_tilesSGBPal0c2 6596
#define tower_anim_tilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tower_anim_tilesSGBPal1c0 6076
#define tower_anim_tilesSGBPal1c1 8935
#define tower_anim_tilesSGBPal1c2 6596
#define tower_anim_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tower_anim_tilesSGBPal2c0 6076
#define tower_anim_tilesSGBPal2c1 8935
#define tower_anim_tilesSGBPal2c2 6596
#define tower_anim_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tower_anim_tilesSGBPal3c0 6076
#define tower_anim_tilesSGBPal3c1 8935
#define tower_anim_tilesSGBPal3c2 6596
#define tower_anim_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tower_anim_tilesCGBPal0c0 32733
#define tower_anim_tilesCGBPal0c1 21140
#define tower_anim_tilesCGBPal0c2 12684
#define tower_anim_tilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define tower_anim_tilesCGBPal1c0 32733
#define tower_anim_tilesCGBPal1c1 21140
#define tower_anim_tilesCGBPal1c2 12684
#define tower_anim_tilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define tower_anim_tilesCGBPal2c0 32733
#define tower_anim_tilesCGBPal2c1 21140
#define tower_anim_tilesCGBPal2c2 12684
#define tower_anim_tilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define tower_anim_tilesCGBPal3c0 8165
#define tower_anim_tilesCGBPal3c1 748
#define tower_anim_tilesCGBPal3c2 1539
#define tower_anim_tilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define tower_anim_tilesCGBPal4c0 8165
#define tower_anim_tilesCGBPal4c1 748
#define tower_anim_tilesCGBPal4c2 1539
#define tower_anim_tilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define tower_anim_tilesCGBPal5c0 8165
#define tower_anim_tilesCGBPal5c1 748
#define tower_anim_tilesCGBPal5c2 1539
#define tower_anim_tilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define tower_anim_tilesCGBPal6c0 8165
#define tower_anim_tilesCGBPal6c1 748
#define tower_anim_tilesCGBPal6c2 1539
#define tower_anim_tilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define tower_anim_tilesCGBPal7c0 8165
#define tower_anim_tilesCGBPal7c1 748
#define tower_anim_tilesCGBPal7c2 1539
#define tower_anim_tilesCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char tower_anim_tilesCGB[];
/* Start of tile array. */
extern const unsigned char tower_anim_tiles[];

/* End of SRC/TOWER_ANIM_TILES.H */
