/*

 SRC/TOWER_ANIM_BKG.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tower_anim_bkgBank 0

/* Super Gameboy palette 0 */
#define tower_anim_bkgSGBPal0c0 6076
#define tower_anim_bkgSGBPal0c1 8935
#define tower_anim_bkgSGBPal0c2 6596
#define tower_anim_bkgSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tower_anim_bkgSGBPal1c0 6076
#define tower_anim_bkgSGBPal1c1 8935
#define tower_anim_bkgSGBPal1c2 6596
#define tower_anim_bkgSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tower_anim_bkgSGBPal2c0 6076
#define tower_anim_bkgSGBPal2c1 8935
#define tower_anim_bkgSGBPal2c2 6596
#define tower_anim_bkgSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tower_anim_bkgSGBPal3c0 6076
#define tower_anim_bkgSGBPal3c1 8935
#define tower_anim_bkgSGBPal3c2 6596
#define tower_anim_bkgSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tower_anim_bkgCGBPal0c0 32733
#define tower_anim_bkgCGBPal0c1 21140
#define tower_anim_bkgCGBPal0c2 12684
#define tower_anim_bkgCGBPal0c3 0

/* Gameboy Color palette 1 */
#define tower_anim_bkgCGBPal1c0 32733
#define tower_anim_bkgCGBPal1c1 21140
#define tower_anim_bkgCGBPal1c2 12684
#define tower_anim_bkgCGBPal1c3 0

/* Gameboy Color palette 2 */
#define tower_anim_bkgCGBPal2c0 32733
#define tower_anim_bkgCGBPal2c1 21140
#define tower_anim_bkgCGBPal2c2 12684
#define tower_anim_bkgCGBPal2c3 0

/* Gameboy Color palette 3 */
#define tower_anim_bkgCGBPal3c0 8165
#define tower_anim_bkgCGBPal3c1 748
#define tower_anim_bkgCGBPal3c2 1539
#define tower_anim_bkgCGBPal3c3 0

/* Gameboy Color palette 4 */
#define tower_anim_bkgCGBPal4c0 8165
#define tower_anim_bkgCGBPal4c1 748
#define tower_anim_bkgCGBPal4c2 1539
#define tower_anim_bkgCGBPal4c3 0

/* Gameboy Color palette 5 */
#define tower_anim_bkgCGBPal5c0 8165
#define tower_anim_bkgCGBPal5c1 748
#define tower_anim_bkgCGBPal5c2 1539
#define tower_anim_bkgCGBPal5c3 0

/* Gameboy Color palette 6 */
#define tower_anim_bkgCGBPal6c0 8165
#define tower_anim_bkgCGBPal6c1 748
#define tower_anim_bkgCGBPal6c2 1539
#define tower_anim_bkgCGBPal6c3 0

/* Gameboy Color palette 7 */
#define tower_anim_bkgCGBPal7c0 8165
#define tower_anim_bkgCGBPal7c1 748
#define tower_anim_bkgCGBPal7c2 1539
#define tower_anim_bkgCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char tower_anim_bkgCGB[];
/* Start of tile array. */
extern unsigned char tower_anim_bkg[];

/* End of SRC/TOWER_ANIM_BKG.H */
