/*

 SRC/TOWER_SPRITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 191

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tower_spriteBank 0

/* Super Gameboy palette 0 */
#define tower_spriteSGBPal0c0 6076
#define tower_spriteSGBPal0c1 8935
#define tower_spriteSGBPal0c2 6596
#define tower_spriteSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tower_spriteSGBPal1c0 6076
#define tower_spriteSGBPal1c1 8935
#define tower_spriteSGBPal1c2 6596
#define tower_spriteSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tower_spriteSGBPal2c0 6076
#define tower_spriteSGBPal2c1 8935
#define tower_spriteSGBPal2c2 6596
#define tower_spriteSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tower_spriteSGBPal3c0 6076
#define tower_spriteSGBPal3c1 8935
#define tower_spriteSGBPal3c2 6596
#define tower_spriteSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tower_spriteCGBPal0c0 32767
#define tower_spriteCGBPal0c1 29660
#define tower_spriteCGBPal0c2 896
#define tower_spriteCGBPal0c3 1442

/* Gameboy Color palette 1 */
#define tower_spriteCGBPal1c0 992
#define tower_spriteCGBPal1c1 30653
#define tower_spriteCGBPal1c2 16912
#define tower_spriteCGBPal1c3 0

/* Gameboy Color palette 2 */
#define tower_spriteCGBPal2c0 992
#define tower_spriteCGBPal2c1 27482
#define tower_spriteCGBPal2c2 16912
#define tower_spriteCGBPal2c3 0

/* Gameboy Color palette 3 */
#define tower_spriteCGBPal3c0 8165
#define tower_spriteCGBPal3c1 748
#define tower_spriteCGBPal3c2 1539
#define tower_spriteCGBPal3c3 0

/* Gameboy Color palette 4 */
#define tower_spriteCGBPal4c0 8165
#define tower_spriteCGBPal4c1 748
#define tower_spriteCGBPal4c2 1539
#define tower_spriteCGBPal4c3 0

/* Gameboy Color palette 5 */
#define tower_spriteCGBPal5c0 8165
#define tower_spriteCGBPal5c1 748
#define tower_spriteCGBPal5c2 1539
#define tower_spriteCGBPal5c3 0

/* Gameboy Color palette 6 */
#define tower_spriteCGBPal6c0 8165
#define tower_spriteCGBPal6c1 748
#define tower_spriteCGBPal6c2 1539
#define tower_spriteCGBPal6c3 0

/* Gameboy Color palette 7 */
#define tower_spriteCGBPal7c0 8165
#define tower_spriteCGBPal7c1 748
#define tower_spriteCGBPal7c2 1539
#define tower_spriteCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char tower_spriteCGB[];
/* Start of tile array. */
extern const unsigned char tower_sprite[];

/* End of SRC/TOWER_SPRITE.H */
