/*

 SRC/TOWER_SPRITE_GHOST.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tower_sprite_ghostBank 0

/* Super Gameboy palette 0 */
#define tower_sprite_ghostSGBPal0c0 6076
#define tower_sprite_ghostSGBPal0c1 8935
#define tower_sprite_ghostSGBPal0c2 6596
#define tower_sprite_ghostSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tower_sprite_ghostSGBPal1c0 6076
#define tower_sprite_ghostSGBPal1c1 8935
#define tower_sprite_ghostSGBPal1c2 6596
#define tower_sprite_ghostSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tower_sprite_ghostSGBPal2c0 6076
#define tower_sprite_ghostSGBPal2c1 8935
#define tower_sprite_ghostSGBPal2c2 6596
#define tower_sprite_ghostSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tower_sprite_ghostSGBPal3c0 6076
#define tower_sprite_ghostSGBPal3c1 8935
#define tower_sprite_ghostSGBPal3c2 6596
#define tower_sprite_ghostSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tower_sprite_ghostCGBPal0c0 32733
#define tower_sprite_ghostCGBPal0c1 21469
#define tower_sprite_ghostCGBPal0c2 947
#define tower_sprite_ghostCGBPal0c3 1481

/* Gameboy Color palette 1 */
#define tower_sprite_ghostCGBPal1c0 992
#define tower_sprite_ghostCGBPal1c1 30653
#define tower_sprite_ghostCGBPal1c2 16912
#define tower_sprite_ghostCGBPal1c3 0

/* Gameboy Color palette 2 */
#define tower_sprite_ghostCGBPal2c0 992
#define tower_sprite_ghostCGBPal2c1 27482
#define tower_sprite_ghostCGBPal2c2 16912
#define tower_sprite_ghostCGBPal2c3 0

/* Gameboy Color palette 3 */
#define tower_sprite_ghostCGBPal3c0 8165
#define tower_sprite_ghostCGBPal3c1 748
#define tower_sprite_ghostCGBPal3c2 1539
#define tower_sprite_ghostCGBPal3c3 0

/* Gameboy Color palette 4 */
#define tower_sprite_ghostCGBPal4c0 8165
#define tower_sprite_ghostCGBPal4c1 748
#define tower_sprite_ghostCGBPal4c2 1539
#define tower_sprite_ghostCGBPal4c3 0

/* Gameboy Color palette 5 */
#define tower_sprite_ghostCGBPal5c0 8165
#define tower_sprite_ghostCGBPal5c1 748
#define tower_sprite_ghostCGBPal5c2 1539
#define tower_sprite_ghostCGBPal5c3 0

/* Gameboy Color palette 6 */
#define tower_sprite_ghostCGBPal6c0 8165
#define tower_sprite_ghostCGBPal6c1 748
#define tower_sprite_ghostCGBPal6c2 1539
#define tower_sprite_ghostCGBPal6c3 0

/* Gameboy Color palette 7 */
#define tower_sprite_ghostCGBPal7c0 8165
#define tower_sprite_ghostCGBPal7c1 748
#define tower_sprite_ghostCGBPal7c2 1539
#define tower_sprite_ghostCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char tower_sprite_ghostCGB[];
/* Start of tile array. */
extern unsigned char tower_sprite_ghost[];

/* End of SRC/TOWER_SPRITE_GHOST.H */
