/*

 VECTOR_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 64

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Vector_TilesBank 0

/* Super Gameboy palette 0 */
#define Vector_TilesSGBPal0c0 6076
#define Vector_TilesSGBPal0c1 8935
#define Vector_TilesSGBPal0c2 6596
#define Vector_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Vector_TilesSGBPal1c0 6076
#define Vector_TilesSGBPal1c1 8935
#define Vector_TilesSGBPal1c2 6596
#define Vector_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Vector_TilesSGBPal2c0 6076
#define Vector_TilesSGBPal2c1 8935
#define Vector_TilesSGBPal2c2 6596
#define Vector_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Vector_TilesSGBPal3c0 6076
#define Vector_TilesSGBPal3c1 8935
#define Vector_TilesSGBPal3c2 6596
#define Vector_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Vector_TilesCGBPal0c0 32233
#define Vector_TilesCGBPal0c1 31674
#define Vector_TilesCGBPal0c2 32642
#define Vector_TilesCGBPal0c3 21088

/* Gameboy Color palette 1 */
#define Vector_TilesCGBPal1c0 31874
#define Vector_TilesCGBPal1c1 32767
#define Vector_TilesCGBPal1c2 21140
#define Vector_TilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Vector_TilesCGBPal2c0 19680
#define Vector_TilesCGBPal2c1 32767
#define Vector_TilesCGBPal2c2 21140
#define Vector_TilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Vector_TilesCGBPal3c0 31344
#define Vector_TilesCGBPal3c1 32767
#define Vector_TilesCGBPal3c2 21140
#define Vector_TilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Vector_TilesCGBPal4c0 31278
#define Vector_TilesCGBPal4c1 32767
#define Vector_TilesCGBPal4c2 21140
#define Vector_TilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Vector_TilesCGBPal5c0 32233
#define Vector_TilesCGBPal5c1 32767
#define Vector_TilesCGBPal5c2 21140
#define Vector_TilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Vector_TilesCGBPal6c0 31640
#define Vector_TilesCGBPal6c1 32767
#define Vector_TilesCGBPal6c2 21140
#define Vector_TilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Vector_TilesCGBPal7c0 32767
#define Vector_TilesCGBPal7c1 31345
#define Vector_TilesCGBPal7c2 29696
#define Vector_TilesCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char Vector_TilesCGB[];
/* Start of tile array. */
extern const unsigned char Vector_Tiles[];

/* End of VECTOR_TILES.H */
