/*

 VECTOR_MAP.H

 Map Include File.

 Info:
   Section       : Map
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : 12_Vector_Tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Vector_MapWidth 32
#define Vector_MapHeight 18
#define Vector_MapBank 0

#define Vector_Map Vector_MapPLN0
extern const unsigned char Vector_MapPLN0[];
extern const unsigned char Vector_MapPLN1[];

/* End of VECTOR_MAP.H */
