/*

 SRC/VECTOR_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 311

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Vector_SpritesBank 0

/* Super Gameboy palette 0 */
#define Vector_SpritesSGBPal0c0 6076
#define Vector_SpritesSGBPal0c1 8935
#define Vector_SpritesSGBPal0c2 6596
#define Vector_SpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Vector_SpritesSGBPal1c0 6076
#define Vector_SpritesSGBPal1c1 8935
#define Vector_SpritesSGBPal1c2 6596
#define Vector_SpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Vector_SpritesSGBPal2c0 6076
#define Vector_SpritesSGBPal2c1 8935
#define Vector_SpritesSGBPal2c2 6596
#define Vector_SpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Vector_SpritesSGBPal3c0 6076
#define Vector_SpritesSGBPal3c1 8935
#define Vector_SpritesSGBPal3c2 6596
#define Vector_SpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Vector_SpritesCGBPal0c0 31507
#define Vector_SpritesCGBPal0c1 30718
#define Vector_SpritesCGBPal0c2 15855
#define Vector_SpritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Vector_SpritesCGBPal1c0 32767
#define Vector_SpritesCGBPal1c1 31345
#define Vector_SpritesCGBPal1c2 29696
#define Vector_SpritesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Vector_SpritesCGBPal2c0 32767
#define Vector_SpritesCGBPal2c1 31345
#define Vector_SpritesCGBPal2c2 29696
#define Vector_SpritesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Vector_SpritesCGBPal3c0 32767
#define Vector_SpritesCGBPal3c1 31345
#define Vector_SpritesCGBPal3c2 29696
#define Vector_SpritesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Vector_SpritesCGBPal4c0 32767
#define Vector_SpritesCGBPal4c1 31345
#define Vector_SpritesCGBPal4c2 29696
#define Vector_SpritesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Vector_SpritesCGBPal5c0 32767
#define Vector_SpritesCGBPal5c1 31345
#define Vector_SpritesCGBPal5c2 29696
#define Vector_SpritesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Vector_SpritesCGBPal6c0 32767
#define Vector_SpritesCGBPal6c1 31345
#define Vector_SpritesCGBPal6c2 29696
#define Vector_SpritesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Vector_SpritesCGBPal7c0 32767
#define Vector_SpritesCGBPal7c1 31345
#define Vector_SpritesCGBPal7c2 29696
#define Vector_SpritesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char Vector_SpritesCGB[];
/* Start of tile array. */
extern unsigned char Vector_Sprites[];

/* End of SRC/VECTOR_SPRITES.H */
