/*

 SRC/VECTOR_ANIM_WATER.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 639

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Vector_Anim_WaterBank 0

/* Super Gameboy palette 0 */
#define Vector_Anim_WaterSGBPal0c0 6076
#define Vector_Anim_WaterSGBPal0c1 8935
#define Vector_Anim_WaterSGBPal0c2 6596
#define Vector_Anim_WaterSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Vector_Anim_WaterSGBPal1c0 6076
#define Vector_Anim_WaterSGBPal1c1 8935
#define Vector_Anim_WaterSGBPal1c2 6596
#define Vector_Anim_WaterSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Vector_Anim_WaterSGBPal2c0 6076
#define Vector_Anim_WaterSGBPal2c1 8935
#define Vector_Anim_WaterSGBPal2c2 6596
#define Vector_Anim_WaterSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Vector_Anim_WaterSGBPal3c0 6076
#define Vector_Anim_WaterSGBPal3c1 8935
#define Vector_Anim_WaterSGBPal3c2 6596
#define Vector_Anim_WaterSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Vector_Anim_WaterCGBPal0c0 31507
#define Vector_Anim_WaterCGBPal0c1 31674
#define Vector_Anim_WaterCGBPal0c2 29666
#define Vector_Anim_WaterCGBPal0c3 23264

/* Gameboy Color palette 1 */
#define Vector_Anim_WaterCGBPal1c0 31507
#define Vector_Anim_WaterCGBPal1c1 32767
#define Vector_Anim_WaterCGBPal1c2 21140
#define Vector_Anim_WaterCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Vector_Anim_WaterCGBPal2c0 32767
#define Vector_Anim_WaterCGBPal2c1 31345
#define Vector_Anim_WaterCGBPal2c2 29696
#define Vector_Anim_WaterCGBPal2c3 0

/* Gameboy Color palette 3 */
#define Vector_Anim_WaterCGBPal3c0 32767
#define Vector_Anim_WaterCGBPal3c1 31345
#define Vector_Anim_WaterCGBPal3c2 29696
#define Vector_Anim_WaterCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Vector_Anim_WaterCGBPal4c0 32767
#define Vector_Anim_WaterCGBPal4c1 31345
#define Vector_Anim_WaterCGBPal4c2 29696
#define Vector_Anim_WaterCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Vector_Anim_WaterCGBPal5c0 32767
#define Vector_Anim_WaterCGBPal5c1 31345
#define Vector_Anim_WaterCGBPal5c2 29696
#define Vector_Anim_WaterCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Vector_Anim_WaterCGBPal6c0 32767
#define Vector_Anim_WaterCGBPal6c1 31345
#define Vector_Anim_WaterCGBPal6c2 29696
#define Vector_Anim_WaterCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Vector_Anim_WaterCGBPal7c0 32767
#define Vector_Anim_WaterCGBPal7c1 31345
#define Vector_Anim_WaterCGBPal7c2 29696
#define Vector_Anim_WaterCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char Vector_Anim_WaterCGB[];
/* Start of tile array. */
extern const unsigned char Vector_Anim_Water[];

/* End of SRC/VECTOR_ANIM_WATER.H */
