/*

 SRC/VECTOR_MAP_WATER.H

 Map Include File.

 Info:
   Section       : Map
   Bank          : 0
   Map size      : 20 x 12
   Tile set      : 12_Vector_Tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Vector_Map_WaterWidth 20
#define Vector_Map_WaterHeight 12
#define Vector_Map_WaterBank 0

#define Vector_Map_Water Vector_Map_WaterPLN0
extern const unsigned char Vector_Map_WaterPLN0[];
extern const unsigned char Vector_Map_WaterPLN1[];

/* End of SRC/VECTOR_MAP_WATER.H */
