/*

 SRC/WIN_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 496 to 511

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Win_TilesBank 0

/* Super Gameboy palette 0 */
#define Win_TilesSGBPal0c0 6076
#define Win_TilesSGBPal0c1 8935
#define Win_TilesSGBPal0c2 6596
#define Win_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Win_TilesSGBPal1c0 6076
#define Win_TilesSGBPal1c1 8935
#define Win_TilesSGBPal1c2 6596
#define Win_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Win_TilesSGBPal2c0 6076
#define Win_TilesSGBPal2c1 8935
#define Win_TilesSGBPal2c2 6596
#define Win_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Win_TilesSGBPal3c0 6076
#define Win_TilesSGBPal3c1 8935
#define Win_TilesSGBPal3c2 6596
#define Win_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Win_TilesCGBPal0c0 26368
#define Win_TilesCGBPal0c1 32767
#define Win_TilesCGBPal0c2 30366
#define Win_TilesCGBPal0c3 5216

/* Gameboy Color palette 1 */
#define Win_TilesCGBPal1c0 26368
#define Win_TilesCGBPal1c1 29887
#define Win_TilesCGBPal1c2 31839
#define Win_TilesCGBPal1c3 5216

/* Gameboy Color palette 2 */
#define Win_TilesCGBPal2c0 26368
#define Win_TilesCGBPal2c1 351
#define Win_TilesCGBPal2c2 125
#define Win_TilesCGBPal2c3 5216

/* Gameboy Color palette 3 */
#define Win_TilesCGBPal3c0 26368
#define Win_TilesCGBPal3c1 32767
#define Win_TilesCGBPal3c2 32767
#define Win_TilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define Win_TilesCGBPal4c0 8165
#define Win_TilesCGBPal4c1 748
#define Win_TilesCGBPal4c2 1539
#define Win_TilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define Win_TilesCGBPal5c0 8165
#define Win_TilesCGBPal5c1 748
#define Win_TilesCGBPal5c2 1539
#define Win_TilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define Win_TilesCGBPal6c0 8165
#define Win_TilesCGBPal6c1 748
#define Win_TilesCGBPal6c2 1539
#define Win_TilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define Win_TilesCGBPal7c0 32767
#define Win_TilesCGBPal7c1 748
#define Win_TilesCGBPal7c2 32767
#define Win_TilesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char Win_TilesCGB[];
/* Start of tile array. */
extern unsigned char Win_Tiles[];

/* End of SRC/WIN_TILES.H */
