/*

 SRC/WINDOW_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : 0_wintiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Window_MapWidth 20
#define Window_MapHeight 18
#define Window_MapBank 0

#define Window_Map Window_MapPLN0
extern unsigned char Window_MapPLN0[];
extern unsigned char Window_MapPLN1[];

/* End of SRC/WINDOW_MAP.H */
