/*

 SRC/ZILOG_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 158

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Zilog_TilesBank 0

/* Super Gameboy palette 0 */
#define Zilog_TilesSGBPal0c0 6076
#define Zilog_TilesSGBPal0c1 8935
#define Zilog_TilesSGBPal0c2 6596
#define Zilog_TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Zilog_TilesSGBPal1c0 6076
#define Zilog_TilesSGBPal1c1 8935
#define Zilog_TilesSGBPal1c2 6596
#define Zilog_TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Zilog_TilesSGBPal2c0 6076
#define Zilog_TilesSGBPal2c1 8935
#define Zilog_TilesSGBPal2c2 6596
#define Zilog_TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Zilog_TilesSGBPal3c0 6076
#define Zilog_TilesSGBPal3c1 8935
#define Zilog_TilesSGBPal3c2 6596
#define Zilog_TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Zilog_TilesCGBPal0c0 21406
#define Zilog_TilesCGBPal0c1 20350
#define Zilog_TilesCGBPal0c2 665
#define Zilog_TilesCGBPal0c3 1390

/* Gameboy Color palette 1 */
#define Zilog_TilesCGBPal1c0 30683
#define Zilog_TilesCGBPal1c1 32589
#define Zilog_TilesCGBPal1c2 32393
#define Zilog_TilesCGBPal1c3 31744

/* Gameboy Color palette 2 */
#define Zilog_TilesCGBPal2c0 30683
#define Zilog_TilesCGBPal2c1 32589
#define Zilog_TilesCGBPal2c2 32393
#define Zilog_TilesCGBPal2c3 31744

/* Gameboy Color palette 3 */
#define Zilog_TilesCGBPal3c0 30683
#define Zilog_TilesCGBPal3c1 32589
#define Zilog_TilesCGBPal3c2 32393
#define Zilog_TilesCGBPal3c3 31744

/* Gameboy Color palette 4 */
#define Zilog_TilesCGBPal4c0 30683
#define Zilog_TilesCGBPal4c1 32589
#define Zilog_TilesCGBPal4c2 32393
#define Zilog_TilesCGBPal4c3 31744

/* Gameboy Color palette 5 */
#define Zilog_TilesCGBPal5c0 30683
#define Zilog_TilesCGBPal5c1 32589
#define Zilog_TilesCGBPal5c2 32393
#define Zilog_TilesCGBPal5c3 31744

/* Gameboy Color palette 6 */
#define Zilog_TilesCGBPal6c0 30683
#define Zilog_TilesCGBPal6c1 32589
#define Zilog_TilesCGBPal6c2 32393
#define Zilog_TilesCGBPal6c3 31744

/* Gameboy Color palette 7 */
#define Zilog_TilesCGBPal7c0 30683
#define Zilog_TilesCGBPal7c1 32589
#define Zilog_TilesCGBPal7c2 32393
#define Zilog_TilesCGBPal7c3 31744
/* CGBpalette entries. */
extern const unsigned char Zilog_TilesCGB[];
/* Start of tile array. */
extern const unsigned char Zilog_Tiles[];

/* End of SRC/ZILOG_TILES.H */
