/*

 SRC/ZILOG_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 12

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Zilog_SpritesBank 0

/* Super Gameboy palette 0 */
#define Zilog_SpritesSGBPal0c0 6076
#define Zilog_SpritesSGBPal0c1 8935
#define Zilog_SpritesSGBPal0c2 6596
#define Zilog_SpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Zilog_SpritesSGBPal1c0 6076
#define Zilog_SpritesSGBPal1c1 8935
#define Zilog_SpritesSGBPal1c2 6596
#define Zilog_SpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Zilog_SpritesSGBPal2c0 6076
#define Zilog_SpritesSGBPal2c1 8935
#define Zilog_SpritesSGBPal2c2 6596
#define Zilog_SpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Zilog_SpritesSGBPal3c0 6076
#define Zilog_SpritesSGBPal3c1 8935
#define Zilog_SpritesSGBPal3c2 6596
#define Zilog_SpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Zilog_SpritesCGBPal0c0 32767
#define Zilog_SpritesCGBPal0c1 29662
#define Zilog_SpritesCGBPal0c2 31967
#define Zilog_SpritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define Zilog_SpritesCGBPal1c0 30683
#define Zilog_SpritesCGBPal1c1 32589
#define Zilog_SpritesCGBPal1c2 32393
#define Zilog_SpritesCGBPal1c3 31744

/* Gameboy Color palette 2 */
#define Zilog_SpritesCGBPal2c0 30683
#define Zilog_SpritesCGBPal2c1 32589
#define Zilog_SpritesCGBPal2c2 32393
#define Zilog_SpritesCGBPal2c3 31744

/* Gameboy Color palette 3 */
#define Zilog_SpritesCGBPal3c0 30683
#define Zilog_SpritesCGBPal3c1 32589
#define Zilog_SpritesCGBPal3c2 32393
#define Zilog_SpritesCGBPal3c3 31744

/* Gameboy Color palette 4 */
#define Zilog_SpritesCGBPal4c0 30683
#define Zilog_SpritesCGBPal4c1 32589
#define Zilog_SpritesCGBPal4c2 32393
#define Zilog_SpritesCGBPal4c3 31744

/* Gameboy Color palette 5 */
#define Zilog_SpritesCGBPal5c0 30683
#define Zilog_SpritesCGBPal5c1 32589
#define Zilog_SpritesCGBPal5c2 32393
#define Zilog_SpritesCGBPal5c3 31744

/* Gameboy Color palette 6 */
#define Zilog_SpritesCGBPal6c0 30683
#define Zilog_SpritesCGBPal6c1 32589
#define Zilog_SpritesCGBPal6c2 32393
#define Zilog_SpritesCGBPal6c3 31744

/* Gameboy Color palette 7 */
#define Zilog_SpritesCGBPal7c0 30683
#define Zilog_SpritesCGBPal7c1 32589
#define Zilog_SpritesCGBPal7c2 32393
#define Zilog_SpritesCGBPal7c3 31744
/* CGBpalette entries. */
extern const unsigned char Zilog_SpritesCGB[];
/* Start of tile array. */
extern const unsigned char Zilog_Sprites[];

/* End of SRC/ZILOG_SPRITES.H */
