/*

 SRC/ZILOG32.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : 1_Zilog_Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Zilog32Width 32
#define Zilog32Height 32
#define Zilog32Bank 0

#define Zilog32 Zilog32PLN0
extern unsigned char Zilog32PLN0[];

/* End of SRC/ZILOG32.H */
